// Code generated by mockery v2.53.2. DO NOT EDIT.

package apps

import (
	api "github.com/databricks/databricks-sdk-go/experimental/api"
	apps "github.com/databricks/databricks-sdk-go/service/apps"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateSpaceOperationInterface is an autogenerated mock type for the UpdateSpaceOperationInterface type
type MockUpdateSpaceOperationInterface struct {
	mock.Mock
}

type MockUpdateSpaceOperationInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateSpaceOperationInterface) EXPECT() *MockUpdateSpaceOperationInterface_Expecter {
	return &MockUpdateSpaceOperationInterface_Expecter{mock: &_m.Mock}
}

// Done provides a mock function with no fields
func (_m *MockUpdateSpaceOperationInterface) Done() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateSpaceOperationInterface_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockUpdateSpaceOperationInterface_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockUpdateSpaceOperationInterface_Expecter) Done() *MockUpdateSpaceOperationInterface_Done_Call {
	return &MockUpdateSpaceOperationInterface_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockUpdateSpaceOperationInterface_Done_Call) Run(run func()) *MockUpdateSpaceOperationInterface_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdateSpaceOperationInterface_Done_Call) Return(_a0 bool, _a1 error) *MockUpdateSpaceOperationInterface_Done_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateSpaceOperationInterface_Done_Call) RunAndReturn(run func() (bool, error)) *MockUpdateSpaceOperationInterface_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function with no fields
func (_m *MockUpdateSpaceOperationInterface) Metadata() (*apps.SpaceUpdate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 *apps.SpaceUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func() (*apps.SpaceUpdate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *apps.SpaceUpdate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apps.SpaceUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateSpaceOperationInterface_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockUpdateSpaceOperationInterface_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockUpdateSpaceOperationInterface_Expecter) Metadata() *MockUpdateSpaceOperationInterface_Metadata_Call {
	return &MockUpdateSpaceOperationInterface_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockUpdateSpaceOperationInterface_Metadata_Call) Run(run func()) *MockUpdateSpaceOperationInterface_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdateSpaceOperationInterface_Metadata_Call) Return(_a0 *apps.SpaceUpdate, _a1 error) *MockUpdateSpaceOperationInterface_Metadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateSpaceOperationInterface_Metadata_Call) RunAndReturn(run func() (*apps.SpaceUpdate, error)) *MockUpdateSpaceOperationInterface_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockUpdateSpaceOperationInterface) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockUpdateSpaceOperationInterface_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockUpdateSpaceOperationInterface_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockUpdateSpaceOperationInterface_Expecter) Name() *MockUpdateSpaceOperationInterface_Name_Call {
	return &MockUpdateSpaceOperationInterface_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockUpdateSpaceOperationInterface_Name_Call) Run(run func()) *MockUpdateSpaceOperationInterface_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdateSpaceOperationInterface_Name_Call) Return(_a0 string) *MockUpdateSpaceOperationInterface_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateSpaceOperationInterface_Name_Call) RunAndReturn(run func() string) *MockUpdateSpaceOperationInterface_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with given fields: ctx, opts
func (_m *MockUpdateSpaceOperationInterface) Wait(ctx context.Context, opts ...api.Option) (*apps.Space, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 *apps.Space
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...api.Option) (*apps.Space, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...api.Option) *apps.Space); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apps.Space)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...api.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateSpaceOperationInterface_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockUpdateSpaceOperationInterface_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...api.Option
func (_e *MockUpdateSpaceOperationInterface_Expecter) Wait(ctx interface{}, opts ...interface{}) *MockUpdateSpaceOperationInterface_Wait_Call {
	return &MockUpdateSpaceOperationInterface_Wait_Call{Call: _e.mock.On("Wait",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockUpdateSpaceOperationInterface_Wait_Call) Run(run func(ctx context.Context, opts ...api.Option)) *MockUpdateSpaceOperationInterface_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]api.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(api.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateSpaceOperationInterface_Wait_Call) Return(_a0 *apps.Space, _a1 error) *MockUpdateSpaceOperationInterface_Wait_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateSpaceOperationInterface_Wait_Call) RunAndReturn(run func(context.Context, ...api.Option) (*apps.Space, error)) *MockUpdateSpaceOperationInterface_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateSpaceOperationInterface creates a new instance of MockUpdateSpaceOperationInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateSpaceOperationInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateSpaceOperationInterface {
	mock := &MockUpdateSpaceOperationInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
