version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[Internal] "
    open-pull-requests-limit: 0 # disable version updates
