with-expecter: true
filename: "mock_{{.InterfaceName | snakecase}}.go"
dir: "experimental/mocks/service/{{.PackageName | snakecase}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
packages:
  github.com/databricks/databricks-sdk-go/service:
    config:
      recursive: true
      include-regex: ".*Interface"