// Code generated by mockery v2.38.0. DO NOT EDIT.

package compute

import (
	context "context"

	compute "github.com/databricks/databricks-sdk-go/service/compute"

	listing "github.com/databricks/databricks-sdk-go/listing"

	mock "github.com/stretchr/testify/mock"
)

// MockInstanceProfilesInterface is an autogenerated mock type for the InstanceProfilesInterface type
type MockInstanceProfilesInterface struct {
	mock.Mock
}

type MockInstanceProfilesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstanceProfilesInterface) EXPECT() *MockInstanceProfilesInterface_Expecter {
	return &MockInstanceProfilesInterface_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, request
func (_m *MockInstanceProfilesInterface) Add(ctx context.Context, request compute.AddInstanceProfile) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, compute.AddInstanceProfile) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstanceProfilesInterface_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockInstanceProfilesInterface_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - request compute.AddInstanceProfile
func (_e *MockInstanceProfilesInterface_Expecter) Add(ctx interface{}, request interface{}) *MockInstanceProfilesInterface_Add_Call {
	return &MockInstanceProfilesInterface_Add_Call{Call: _e.mock.On("Add", ctx, request)}
}

func (_c *MockInstanceProfilesInterface_Add_Call) Run(run func(ctx context.Context, request compute.AddInstanceProfile)) *MockInstanceProfilesInterface_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(compute.AddInstanceProfile))
	})
	return _c
}

func (_c *MockInstanceProfilesInterface_Add_Call) Return(_a0 error) *MockInstanceProfilesInterface_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceProfilesInterface_Add_Call) RunAndReturn(run func(context.Context, compute.AddInstanceProfile) error) *MockInstanceProfilesInterface_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Edit provides a mock function with given fields: ctx, request
func (_m *MockInstanceProfilesInterface) Edit(ctx context.Context, request compute.InstanceProfile) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, compute.InstanceProfile) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstanceProfilesInterface_Edit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Edit'
type MockInstanceProfilesInterface_Edit_Call struct {
	*mock.Call
}

// Edit is a helper method to define mock.On call
//   - ctx context.Context
//   - request compute.InstanceProfile
func (_e *MockInstanceProfilesInterface_Expecter) Edit(ctx interface{}, request interface{}) *MockInstanceProfilesInterface_Edit_Call {
	return &MockInstanceProfilesInterface_Edit_Call{Call: _e.mock.On("Edit", ctx, request)}
}

func (_c *MockInstanceProfilesInterface_Edit_Call) Run(run func(ctx context.Context, request compute.InstanceProfile)) *MockInstanceProfilesInterface_Edit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(compute.InstanceProfile))
	})
	return _c
}

func (_c *MockInstanceProfilesInterface_Edit_Call) Return(_a0 error) *MockInstanceProfilesInterface_Edit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceProfilesInterface_Edit_Call) RunAndReturn(run func(context.Context, compute.InstanceProfile) error) *MockInstanceProfilesInterface_Edit_Call {
	_c.Call.Return(run)
	return _c
}

// Impl provides a mock function with given fields:
func (_m *MockInstanceProfilesInterface) Impl() compute.InstanceProfilesService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Impl")
	}

	var r0 compute.InstanceProfilesService
	if rf, ok := ret.Get(0).(func() compute.InstanceProfilesService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(compute.InstanceProfilesService)
		}
	}

	return r0
}

// MockInstanceProfilesInterface_Impl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Impl'
type MockInstanceProfilesInterface_Impl_Call struct {
	*mock.Call
}

// Impl is a helper method to define mock.On call
func (_e *MockInstanceProfilesInterface_Expecter) Impl() *MockInstanceProfilesInterface_Impl_Call {
	return &MockInstanceProfilesInterface_Impl_Call{Call: _e.mock.On("Impl")}
}

func (_c *MockInstanceProfilesInterface_Impl_Call) Run(run func()) *MockInstanceProfilesInterface_Impl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInstanceProfilesInterface_Impl_Call) Return(_a0 compute.InstanceProfilesService) *MockInstanceProfilesInterface_Impl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceProfilesInterface_Impl_Call) RunAndReturn(run func() compute.InstanceProfilesService) *MockInstanceProfilesInterface_Impl_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockInstanceProfilesInterface) List(ctx context.Context) *listing.PaginatingIterator[struct{}, *compute.ListInstanceProfilesResponse, compute.InstanceProfile] {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *listing.PaginatingIterator[struct{}, *compute.ListInstanceProfilesResponse, compute.InstanceProfile]
	if rf, ok := ret.Get(0).(func(context.Context) *listing.PaginatingIterator[struct{}, *compute.ListInstanceProfilesResponse, compute.InstanceProfile]); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*listing.PaginatingIterator[struct{}, *compute.ListInstanceProfilesResponse, compute.InstanceProfile])
		}
	}

	return r0
}

// MockInstanceProfilesInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockInstanceProfilesInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstanceProfilesInterface_Expecter) List(ctx interface{}) *MockInstanceProfilesInterface_List_Call {
	return &MockInstanceProfilesInterface_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockInstanceProfilesInterface_List_Call) Run(run func(ctx context.Context)) *MockInstanceProfilesInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInstanceProfilesInterface_List_Call) Return(_a0 *listing.PaginatingIterator[struct{}, *compute.ListInstanceProfilesResponse, compute.InstanceProfile]) *MockInstanceProfilesInterface_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceProfilesInterface_List_Call) RunAndReturn(run func(context.Context) *listing.PaginatingIterator[struct{}, *compute.ListInstanceProfilesResponse, compute.InstanceProfile]) *MockInstanceProfilesInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx
func (_m *MockInstanceProfilesInterface) ListAll(ctx context.Context) ([]compute.InstanceProfile, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []compute.InstanceProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]compute.InstanceProfile, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []compute.InstanceProfile); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compute.InstanceProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceProfilesInterface_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockInstanceProfilesInterface_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstanceProfilesInterface_Expecter) ListAll(ctx interface{}) *MockInstanceProfilesInterface_ListAll_Call {
	return &MockInstanceProfilesInterface_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockInstanceProfilesInterface_ListAll_Call) Run(run func(ctx context.Context)) *MockInstanceProfilesInterface_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInstanceProfilesInterface_ListAll_Call) Return(_a0 []compute.InstanceProfile, _a1 error) *MockInstanceProfilesInterface_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInstanceProfilesInterface_ListAll_Call) RunAndReturn(run func(context.Context) ([]compute.InstanceProfile, error)) *MockInstanceProfilesInterface_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, request
func (_m *MockInstanceProfilesInterface) Remove(ctx context.Context, request compute.RemoveInstanceProfile) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, compute.RemoveInstanceProfile) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstanceProfilesInterface_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockInstanceProfilesInterface_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - request compute.RemoveInstanceProfile
func (_e *MockInstanceProfilesInterface_Expecter) Remove(ctx interface{}, request interface{}) *MockInstanceProfilesInterface_Remove_Call {
	return &MockInstanceProfilesInterface_Remove_Call{Call: _e.mock.On("Remove", ctx, request)}
}

func (_c *MockInstanceProfilesInterface_Remove_Call) Run(run func(ctx context.Context, request compute.RemoveInstanceProfile)) *MockInstanceProfilesInterface_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(compute.RemoveInstanceProfile))
	})
	return _c
}

func (_c *MockInstanceProfilesInterface_Remove_Call) Return(_a0 error) *MockInstanceProfilesInterface_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceProfilesInterface_Remove_Call) RunAndReturn(run func(context.Context, compute.RemoveInstanceProfile) error) *MockInstanceProfilesInterface_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveByInstanceProfileArn provides a mock function with given fields: ctx, instanceProfileArn
func (_m *MockInstanceProfilesInterface) RemoveByInstanceProfileArn(ctx context.Context, instanceProfileArn string) error {
	ret := _m.Called(ctx, instanceProfileArn)

	if len(ret) == 0 {
		panic("no return value specified for RemoveByInstanceProfileArn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, instanceProfileArn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstanceProfilesInterface_RemoveByInstanceProfileArn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveByInstanceProfileArn'
type MockInstanceProfilesInterface_RemoveByInstanceProfileArn_Call struct {
	*mock.Call
}

// RemoveByInstanceProfileArn is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceProfileArn string
func (_e *MockInstanceProfilesInterface_Expecter) RemoveByInstanceProfileArn(ctx interface{}, instanceProfileArn interface{}) *MockInstanceProfilesInterface_RemoveByInstanceProfileArn_Call {
	return &MockInstanceProfilesInterface_RemoveByInstanceProfileArn_Call{Call: _e.mock.On("RemoveByInstanceProfileArn", ctx, instanceProfileArn)}
}

func (_c *MockInstanceProfilesInterface_RemoveByInstanceProfileArn_Call) Run(run func(ctx context.Context, instanceProfileArn string)) *MockInstanceProfilesInterface_RemoveByInstanceProfileArn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInstanceProfilesInterface_RemoveByInstanceProfileArn_Call) Return(_a0 error) *MockInstanceProfilesInterface_RemoveByInstanceProfileArn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceProfilesInterface_RemoveByInstanceProfileArn_Call) RunAndReturn(run func(context.Context, string) error) *MockInstanceProfilesInterface_RemoveByInstanceProfileArn_Call {
	_c.Call.Return(run)
	return _c
}

// WithImpl provides a mock function with given fields: impl
func (_m *MockInstanceProfilesInterface) WithImpl(impl compute.InstanceProfilesService) compute.InstanceProfilesInterface {
	ret := _m.Called(impl)

	if len(ret) == 0 {
		panic("no return value specified for WithImpl")
	}

	var r0 compute.InstanceProfilesInterface
	if rf, ok := ret.Get(0).(func(compute.InstanceProfilesService) compute.InstanceProfilesInterface); ok {
		r0 = rf(impl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(compute.InstanceProfilesInterface)
		}
	}

	return r0
}

// MockInstanceProfilesInterface_WithImpl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithImpl'
type MockInstanceProfilesInterface_WithImpl_Call struct {
	*mock.Call
}

// WithImpl is a helper method to define mock.On call
//   - impl compute.InstanceProfilesService
func (_e *MockInstanceProfilesInterface_Expecter) WithImpl(impl interface{}) *MockInstanceProfilesInterface_WithImpl_Call {
	return &MockInstanceProfilesInterface_WithImpl_Call{Call: _e.mock.On("WithImpl", impl)}
}

func (_c *MockInstanceProfilesInterface_WithImpl_Call) Run(run func(impl compute.InstanceProfilesService)) *MockInstanceProfilesInterface_WithImpl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(compute.InstanceProfilesService))
	})
	return _c
}

func (_c *MockInstanceProfilesInterface_WithImpl_Call) Return(_a0 compute.InstanceProfilesInterface) *MockInstanceProfilesInterface_WithImpl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceProfilesInterface_WithImpl_Call) RunAndReturn(run func(compute.InstanceProfilesService) compute.InstanceProfilesInterface) *MockInstanceProfilesInterface_WithImpl_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstanceProfilesInterface creates a new instance of MockInstanceProfilesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstanceProfilesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstanceProfilesInterface {
	mock := &MockInstanceProfilesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
