// Code generated by mockery v2.43.0. DO NOT EDIT.

package provisioning

import (
	context "context"

	provisioning "github.com/databricks/databricks-sdk-go/service/provisioning"
	mock "github.com/stretchr/testify/mock"
)

// MockStorageInterface is an autogenerated mock type for the StorageInterface type
type MockStorageInterface struct {
	mock.Mock
}

type MockStorageInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageInterface) EXPECT() *MockStorageInterface_Expecter {
	return &MockStorageInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, request
func (_m *MockStorageInterface) Create(ctx context.Context, request provisioning.CreateStorageConfigurationRequest) (*provisioning.StorageConfiguration, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *provisioning.StorageConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, provisioning.CreateStorageConfigurationRequest) (*provisioning.StorageConfiguration, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, provisioning.CreateStorageConfigurationRequest) *provisioning.StorageConfiguration); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provisioning.StorageConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, provisioning.CreateStorageConfigurationRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorageInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request provisioning.CreateStorageConfigurationRequest
func (_e *MockStorageInterface_Expecter) Create(ctx interface{}, request interface{}) *MockStorageInterface_Create_Call {
	return &MockStorageInterface_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockStorageInterface_Create_Call) Run(run func(ctx context.Context, request provisioning.CreateStorageConfigurationRequest)) *MockStorageInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(provisioning.CreateStorageConfigurationRequest))
	})
	return _c
}

func (_c *MockStorageInterface_Create_Call) Return(_a0 *provisioning.StorageConfiguration, _a1 error) *MockStorageInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageInterface_Create_Call) RunAndReturn(run func(context.Context, provisioning.CreateStorageConfigurationRequest) (*provisioning.StorageConfiguration, error)) *MockStorageInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, request
func (_m *MockStorageInterface) Delete(ctx context.Context, request provisioning.DeleteStorageRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, provisioning.DeleteStorageRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorageInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorageInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - request provisioning.DeleteStorageRequest
func (_e *MockStorageInterface_Expecter) Delete(ctx interface{}, request interface{}) *MockStorageInterface_Delete_Call {
	return &MockStorageInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, request)}
}

func (_c *MockStorageInterface_Delete_Call) Run(run func(ctx context.Context, request provisioning.DeleteStorageRequest)) *MockStorageInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(provisioning.DeleteStorageRequest))
	})
	return _c
}

func (_c *MockStorageInterface_Delete_Call) Return(_a0 error) *MockStorageInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageInterface_Delete_Call) RunAndReturn(run func(context.Context, provisioning.DeleteStorageRequest) error) *MockStorageInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByStorageConfigurationId provides a mock function with given fields: ctx, storageConfigurationId
func (_m *MockStorageInterface) DeleteByStorageConfigurationId(ctx context.Context, storageConfigurationId string) error {
	ret := _m.Called(ctx, storageConfigurationId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByStorageConfigurationId")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, storageConfigurationId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorageInterface_DeleteByStorageConfigurationId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByStorageConfigurationId'
type MockStorageInterface_DeleteByStorageConfigurationId_Call struct {
	*mock.Call
}

// DeleteByStorageConfigurationId is a helper method to define mock.On call
//   - ctx context.Context
//   - storageConfigurationId string
func (_e *MockStorageInterface_Expecter) DeleteByStorageConfigurationId(ctx interface{}, storageConfigurationId interface{}) *MockStorageInterface_DeleteByStorageConfigurationId_Call {
	return &MockStorageInterface_DeleteByStorageConfigurationId_Call{Call: _e.mock.On("DeleteByStorageConfigurationId", ctx, storageConfigurationId)}
}

func (_c *MockStorageInterface_DeleteByStorageConfigurationId_Call) Run(run func(ctx context.Context, storageConfigurationId string)) *MockStorageInterface_DeleteByStorageConfigurationId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorageInterface_DeleteByStorageConfigurationId_Call) Return(_a0 error) *MockStorageInterface_DeleteByStorageConfigurationId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageInterface_DeleteByStorageConfigurationId_Call) RunAndReturn(run func(context.Context, string) error) *MockStorageInterface_DeleteByStorageConfigurationId_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, request
func (_m *MockStorageInterface) Get(ctx context.Context, request provisioning.GetStorageRequest) (*provisioning.StorageConfiguration, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *provisioning.StorageConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, provisioning.GetStorageRequest) (*provisioning.StorageConfiguration, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, provisioning.GetStorageRequest) *provisioning.StorageConfiguration); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provisioning.StorageConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, provisioning.GetStorageRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorageInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - request provisioning.GetStorageRequest
func (_e *MockStorageInterface_Expecter) Get(ctx interface{}, request interface{}) *MockStorageInterface_Get_Call {
	return &MockStorageInterface_Get_Call{Call: _e.mock.On("Get", ctx, request)}
}

func (_c *MockStorageInterface_Get_Call) Run(run func(ctx context.Context, request provisioning.GetStorageRequest)) *MockStorageInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(provisioning.GetStorageRequest))
	})
	return _c
}

func (_c *MockStorageInterface_Get_Call) Return(_a0 *provisioning.StorageConfiguration, _a1 error) *MockStorageInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageInterface_Get_Call) RunAndReturn(run func(context.Context, provisioning.GetStorageRequest) (*provisioning.StorageConfiguration, error)) *MockStorageInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStorageConfigurationId provides a mock function with given fields: ctx, storageConfigurationId
func (_m *MockStorageInterface) GetByStorageConfigurationId(ctx context.Context, storageConfigurationId string) (*provisioning.StorageConfiguration, error) {
	ret := _m.Called(ctx, storageConfigurationId)

	if len(ret) == 0 {
		panic("no return value specified for GetByStorageConfigurationId")
	}

	var r0 *provisioning.StorageConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*provisioning.StorageConfiguration, error)); ok {
		return rf(ctx, storageConfigurationId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *provisioning.StorageConfiguration); ok {
		r0 = rf(ctx, storageConfigurationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provisioning.StorageConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storageConfigurationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageInterface_GetByStorageConfigurationId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStorageConfigurationId'
type MockStorageInterface_GetByStorageConfigurationId_Call struct {
	*mock.Call
}

// GetByStorageConfigurationId is a helper method to define mock.On call
//   - ctx context.Context
//   - storageConfigurationId string
func (_e *MockStorageInterface_Expecter) GetByStorageConfigurationId(ctx interface{}, storageConfigurationId interface{}) *MockStorageInterface_GetByStorageConfigurationId_Call {
	return &MockStorageInterface_GetByStorageConfigurationId_Call{Call: _e.mock.On("GetByStorageConfigurationId", ctx, storageConfigurationId)}
}

func (_c *MockStorageInterface_GetByStorageConfigurationId_Call) Run(run func(ctx context.Context, storageConfigurationId string)) *MockStorageInterface_GetByStorageConfigurationId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorageInterface_GetByStorageConfigurationId_Call) Return(_a0 *provisioning.StorageConfiguration, _a1 error) *MockStorageInterface_GetByStorageConfigurationId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageInterface_GetByStorageConfigurationId_Call) RunAndReturn(run func(context.Context, string) (*provisioning.StorageConfiguration, error)) *MockStorageInterface_GetByStorageConfigurationId_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStorageConfigurationName provides a mock function with given fields: ctx, name
func (_m *MockStorageInterface) GetByStorageConfigurationName(ctx context.Context, name string) (*provisioning.StorageConfiguration, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByStorageConfigurationName")
	}

	var r0 *provisioning.StorageConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*provisioning.StorageConfiguration, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *provisioning.StorageConfiguration); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provisioning.StorageConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageInterface_GetByStorageConfigurationName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStorageConfigurationName'
type MockStorageInterface_GetByStorageConfigurationName_Call struct {
	*mock.Call
}

// GetByStorageConfigurationName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockStorageInterface_Expecter) GetByStorageConfigurationName(ctx interface{}, name interface{}) *MockStorageInterface_GetByStorageConfigurationName_Call {
	return &MockStorageInterface_GetByStorageConfigurationName_Call{Call: _e.mock.On("GetByStorageConfigurationName", ctx, name)}
}

func (_c *MockStorageInterface_GetByStorageConfigurationName_Call) Run(run func(ctx context.Context, name string)) *MockStorageInterface_GetByStorageConfigurationName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorageInterface_GetByStorageConfigurationName_Call) Return(_a0 *provisioning.StorageConfiguration, _a1 error) *MockStorageInterface_GetByStorageConfigurationName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageInterface_GetByStorageConfigurationName_Call) RunAndReturn(run func(context.Context, string) (*provisioning.StorageConfiguration, error)) *MockStorageInterface_GetByStorageConfigurationName_Call {
	_c.Call.Return(run)
	return _c
}

// Impl provides a mock function with given fields:
func (_m *MockStorageInterface) Impl() provisioning.StorageService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Impl")
	}

	var r0 provisioning.StorageService
	if rf, ok := ret.Get(0).(func() provisioning.StorageService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provisioning.StorageService)
		}
	}

	return r0
}

// MockStorageInterface_Impl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Impl'
type MockStorageInterface_Impl_Call struct {
	*mock.Call
}

// Impl is a helper method to define mock.On call
func (_e *MockStorageInterface_Expecter) Impl() *MockStorageInterface_Impl_Call {
	return &MockStorageInterface_Impl_Call{Call: _e.mock.On("Impl")}
}

func (_c *MockStorageInterface_Impl_Call) Run(run func()) *MockStorageInterface_Impl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageInterface_Impl_Call) Return(_a0 provisioning.StorageService) *MockStorageInterface_Impl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageInterface_Impl_Call) RunAndReturn(run func() provisioning.StorageService) *MockStorageInterface_Impl_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockStorageInterface) List(ctx context.Context) ([]provisioning.StorageConfiguration, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []provisioning.StorageConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]provisioning.StorageConfiguration, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []provisioning.StorageConfiguration); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]provisioning.StorageConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStorageInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorageInterface_Expecter) List(ctx interface{}) *MockStorageInterface_List_Call {
	return &MockStorageInterface_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockStorageInterface_List_Call) Run(run func(ctx context.Context)) *MockStorageInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorageInterface_List_Call) Return(_a0 []provisioning.StorageConfiguration, _a1 error) *MockStorageInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageInterface_List_Call) RunAndReturn(run func(context.Context) ([]provisioning.StorageConfiguration, error)) *MockStorageInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap provides a mock function with given fields: ctx
func (_m *MockStorageInterface) StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap(ctx context.Context) (map[string]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageInterface_StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap'
type MockStorageInterface_StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap_Call struct {
	*mock.Call
}

// StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorageInterface_Expecter) StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap(ctx interface{}) *MockStorageInterface_StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap_Call {
	return &MockStorageInterface_StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap_Call{Call: _e.mock.On("StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap", ctx)}
}

func (_c *MockStorageInterface_StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap_Call) Run(run func(ctx context.Context)) *MockStorageInterface_StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorageInterface_StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap_Call) Return(_a0 map[string]string, _a1 error) *MockStorageInterface_StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageInterface_StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap_Call) RunAndReturn(run func(context.Context) (map[string]string, error)) *MockStorageInterface_StorageConfigurationStorageConfigurationNameToStorageConfigurationIdMap_Call {
	_c.Call.Return(run)
	return _c
}

// WithImpl provides a mock function with given fields: impl
func (_m *MockStorageInterface) WithImpl(impl provisioning.StorageService) provisioning.StorageInterface {
	ret := _m.Called(impl)

	if len(ret) == 0 {
		panic("no return value specified for WithImpl")
	}

	var r0 provisioning.StorageInterface
	if rf, ok := ret.Get(0).(func(provisioning.StorageService) provisioning.StorageInterface); ok {
		r0 = rf(impl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provisioning.StorageInterface)
		}
	}

	return r0
}

// MockStorageInterface_WithImpl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithImpl'
type MockStorageInterface_WithImpl_Call struct {
	*mock.Call
}

// WithImpl is a helper method to define mock.On call
//   - impl provisioning.StorageService
func (_e *MockStorageInterface_Expecter) WithImpl(impl interface{}) *MockStorageInterface_WithImpl_Call {
	return &MockStorageInterface_WithImpl_Call{Call: _e.mock.On("WithImpl", impl)}
}

func (_c *MockStorageInterface_WithImpl_Call) Run(run func(impl provisioning.StorageService)) *MockStorageInterface_WithImpl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(provisioning.StorageService))
	})
	return _c
}

func (_c *MockStorageInterface_WithImpl_Call) Return(_a0 provisioning.StorageInterface) *MockStorageInterface_WithImpl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageInterface_WithImpl_Call) RunAndReturn(run func(provisioning.StorageService) provisioning.StorageInterface) *MockStorageInterface_WithImpl_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorageInterface creates a new instance of MockStorageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageInterface {
	mock := &MockStorageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
