// Code generated by mockery v2.38.0. DO NOT EDIT.

package settings

import (
	context "context"

	listing "github.com/databricks/databricks-sdk-go/listing"
	mock "github.com/stretchr/testify/mock"

	settings "github.com/databricks/databricks-sdk-go/service/settings"
)

// MockNetworkConnectivityAPIInterface is an autogenerated mock type for the NetworkConnectivityAPIInterface type
type MockNetworkConnectivityAPIInterface struct {
	mock.Mock
}

type MockNetworkConnectivityAPIInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNetworkConnectivityAPIInterface) EXPECT() *MockNetworkConnectivityAPIInterface_Expecter {
	return &MockNetworkConnectivityAPIInterface_Expecter{mock: &_m.Mock}
}

// CreateNetworkConnectivityConfiguration provides a mock function with given fields: ctx, request
func (_m *MockNetworkConnectivityAPIInterface) CreateNetworkConnectivityConfiguration(ctx context.Context, request settings.CreateNetworkConnectivityConfigRequest) (*settings.NetworkConnectivityConfiguration, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateNetworkConnectivityConfiguration")
	}

	var r0 *settings.NetworkConnectivityConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, settings.CreateNetworkConnectivityConfigRequest) (*settings.NetworkConnectivityConfiguration, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, settings.CreateNetworkConnectivityConfigRequest) *settings.NetworkConnectivityConfiguration); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settings.NetworkConnectivityConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, settings.CreateNetworkConnectivityConfigRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNetworkConnectivityAPIInterface_CreateNetworkConnectivityConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNetworkConnectivityConfiguration'
type MockNetworkConnectivityAPIInterface_CreateNetworkConnectivityConfiguration_Call struct {
	*mock.Call
}

// CreateNetworkConnectivityConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - request settings.CreateNetworkConnectivityConfigRequest
func (_e *MockNetworkConnectivityAPIInterface_Expecter) CreateNetworkConnectivityConfiguration(ctx interface{}, request interface{}) *MockNetworkConnectivityAPIInterface_CreateNetworkConnectivityConfiguration_Call {
	return &MockNetworkConnectivityAPIInterface_CreateNetworkConnectivityConfiguration_Call{Call: _e.mock.On("CreateNetworkConnectivityConfiguration", ctx, request)}
}

func (_c *MockNetworkConnectivityAPIInterface_CreateNetworkConnectivityConfiguration_Call) Run(run func(ctx context.Context, request settings.CreateNetworkConnectivityConfigRequest)) *MockNetworkConnectivityAPIInterface_CreateNetworkConnectivityConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(settings.CreateNetworkConnectivityConfigRequest))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_CreateNetworkConnectivityConfiguration_Call) Return(_a0 *settings.NetworkConnectivityConfiguration, _a1 error) *MockNetworkConnectivityAPIInterface_CreateNetworkConnectivityConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_CreateNetworkConnectivityConfiguration_Call) RunAndReturn(run func(context.Context, settings.CreateNetworkConnectivityConfigRequest) (*settings.NetworkConnectivityConfiguration, error)) *MockNetworkConnectivityAPIInterface_CreateNetworkConnectivityConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePrivateEndpointRule provides a mock function with given fields: ctx, request
func (_m *MockNetworkConnectivityAPIInterface) CreatePrivateEndpointRule(ctx context.Context, request settings.CreatePrivateEndpointRuleRequest) (*settings.NccAzurePrivateEndpointRule, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreatePrivateEndpointRule")
	}

	var r0 *settings.NccAzurePrivateEndpointRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, settings.CreatePrivateEndpointRuleRequest) (*settings.NccAzurePrivateEndpointRule, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, settings.CreatePrivateEndpointRuleRequest) *settings.NccAzurePrivateEndpointRule); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settings.NccAzurePrivateEndpointRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, settings.CreatePrivateEndpointRuleRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNetworkConnectivityAPIInterface_CreatePrivateEndpointRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePrivateEndpointRule'
type MockNetworkConnectivityAPIInterface_CreatePrivateEndpointRule_Call struct {
	*mock.Call
}

// CreatePrivateEndpointRule is a helper method to define mock.On call
//   - ctx context.Context
//   - request settings.CreatePrivateEndpointRuleRequest
func (_e *MockNetworkConnectivityAPIInterface_Expecter) CreatePrivateEndpointRule(ctx interface{}, request interface{}) *MockNetworkConnectivityAPIInterface_CreatePrivateEndpointRule_Call {
	return &MockNetworkConnectivityAPIInterface_CreatePrivateEndpointRule_Call{Call: _e.mock.On("CreatePrivateEndpointRule", ctx, request)}
}

func (_c *MockNetworkConnectivityAPIInterface_CreatePrivateEndpointRule_Call) Run(run func(ctx context.Context, request settings.CreatePrivateEndpointRuleRequest)) *MockNetworkConnectivityAPIInterface_CreatePrivateEndpointRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(settings.CreatePrivateEndpointRuleRequest))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_CreatePrivateEndpointRule_Call) Return(_a0 *settings.NccAzurePrivateEndpointRule, _a1 error) *MockNetworkConnectivityAPIInterface_CreatePrivateEndpointRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_CreatePrivateEndpointRule_Call) RunAndReturn(run func(context.Context, settings.CreatePrivateEndpointRuleRequest) (*settings.NccAzurePrivateEndpointRule, error)) *MockNetworkConnectivityAPIInterface_CreatePrivateEndpointRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNetworkConnectivityConfiguration provides a mock function with given fields: ctx, request
func (_m *MockNetworkConnectivityAPIInterface) DeleteNetworkConnectivityConfiguration(ctx context.Context, request settings.DeleteNetworkConnectivityConfigurationRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNetworkConnectivityConfiguration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, settings.DeleteNetworkConnectivityConfigurationRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNetworkConnectivityConfiguration'
type MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfiguration_Call struct {
	*mock.Call
}

// DeleteNetworkConnectivityConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - request settings.DeleteNetworkConnectivityConfigurationRequest
func (_e *MockNetworkConnectivityAPIInterface_Expecter) DeleteNetworkConnectivityConfiguration(ctx interface{}, request interface{}) *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfiguration_Call {
	return &MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfiguration_Call{Call: _e.mock.On("DeleteNetworkConnectivityConfiguration", ctx, request)}
}

func (_c *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfiguration_Call) Run(run func(ctx context.Context, request settings.DeleteNetworkConnectivityConfigurationRequest)) *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(settings.DeleteNetworkConnectivityConfigurationRequest))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfiguration_Call) Return(_a0 error) *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfiguration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfiguration_Call) RunAndReturn(run func(context.Context, settings.DeleteNetworkConnectivityConfigurationRequest) error) *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId provides a mock function with given fields: ctx, networkConnectivityConfigId
func (_m *MockNetworkConnectivityAPIInterface) DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId(ctx context.Context, networkConnectivityConfigId string) error {
	ret := _m.Called(ctx, networkConnectivityConfigId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, networkConnectivityConfigId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId'
type MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call struct {
	*mock.Call
}

// DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId is a helper method to define mock.On call
//   - ctx context.Context
//   - networkConnectivityConfigId string
func (_e *MockNetworkConnectivityAPIInterface_Expecter) DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId(ctx interface{}, networkConnectivityConfigId interface{}) *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call {
	return &MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call{Call: _e.mock.On("DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId", ctx, networkConnectivityConfigId)}
}

func (_c *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call) Run(run func(ctx context.Context, networkConnectivityConfigId string)) *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call) Return(_a0 error) *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call) RunAndReturn(run func(context.Context, string) error) *MockNetworkConnectivityAPIInterface_DeleteNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePrivateEndpointRule provides a mock function with given fields: ctx, request
func (_m *MockNetworkConnectivityAPIInterface) DeletePrivateEndpointRule(ctx context.Context, request settings.DeletePrivateEndpointRuleRequest) (*settings.NccAzurePrivateEndpointRule, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeletePrivateEndpointRule")
	}

	var r0 *settings.NccAzurePrivateEndpointRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, settings.DeletePrivateEndpointRuleRequest) (*settings.NccAzurePrivateEndpointRule, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, settings.DeletePrivateEndpointRuleRequest) *settings.NccAzurePrivateEndpointRule); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settings.NccAzurePrivateEndpointRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, settings.DeletePrivateEndpointRuleRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePrivateEndpointRule'
type MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRule_Call struct {
	*mock.Call
}

// DeletePrivateEndpointRule is a helper method to define mock.On call
//   - ctx context.Context
//   - request settings.DeletePrivateEndpointRuleRequest
func (_e *MockNetworkConnectivityAPIInterface_Expecter) DeletePrivateEndpointRule(ctx interface{}, request interface{}) *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRule_Call {
	return &MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRule_Call{Call: _e.mock.On("DeletePrivateEndpointRule", ctx, request)}
}

func (_c *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRule_Call) Run(run func(ctx context.Context, request settings.DeletePrivateEndpointRuleRequest)) *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(settings.DeletePrivateEndpointRuleRequest))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRule_Call) Return(_a0 *settings.NccAzurePrivateEndpointRule, _a1 error) *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRule_Call) RunAndReturn(run func(context.Context, settings.DeletePrivateEndpointRuleRequest) (*settings.NccAzurePrivateEndpointRule, error)) *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId provides a mock function with given fields: ctx, networkConnectivityConfigId, privateEndpointRuleId
func (_m *MockNetworkConnectivityAPIInterface) DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId(ctx context.Context, networkConnectivityConfigId string, privateEndpointRuleId string) (*settings.NccAzurePrivateEndpointRule, error) {
	ret := _m.Called(ctx, networkConnectivityConfigId, privateEndpointRuleId)

	if len(ret) == 0 {
		panic("no return value specified for DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId")
	}

	var r0 *settings.NccAzurePrivateEndpointRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*settings.NccAzurePrivateEndpointRule, error)); ok {
		return rf(ctx, networkConnectivityConfigId, privateEndpointRuleId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *settings.NccAzurePrivateEndpointRule); ok {
		r0 = rf(ctx, networkConnectivityConfigId, privateEndpointRuleId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settings.NccAzurePrivateEndpointRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, networkConnectivityConfigId, privateEndpointRuleId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId'
type MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call struct {
	*mock.Call
}

// DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId is a helper method to define mock.On call
//   - ctx context.Context
//   - networkConnectivityConfigId string
//   - privateEndpointRuleId string
func (_e *MockNetworkConnectivityAPIInterface_Expecter) DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId(ctx interface{}, networkConnectivityConfigId interface{}, privateEndpointRuleId interface{}) *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call {
	return &MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call{Call: _e.mock.On("DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId", ctx, networkConnectivityConfigId, privateEndpointRuleId)}
}

func (_c *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call) Run(run func(ctx context.Context, networkConnectivityConfigId string, privateEndpointRuleId string)) *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call) Return(_a0 *settings.NccAzurePrivateEndpointRule, _a1 error) *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call) RunAndReturn(run func(context.Context, string, string) (*settings.NccAzurePrivateEndpointRule, error)) *MockNetworkConnectivityAPIInterface_DeletePrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetworkConnectivityConfiguration provides a mock function with given fields: ctx, request
func (_m *MockNetworkConnectivityAPIInterface) GetNetworkConnectivityConfiguration(ctx context.Context, request settings.GetNetworkConnectivityConfigurationRequest) (*settings.NetworkConnectivityConfiguration, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetNetworkConnectivityConfiguration")
	}

	var r0 *settings.NetworkConnectivityConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, settings.GetNetworkConnectivityConfigurationRequest) (*settings.NetworkConnectivityConfiguration, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, settings.GetNetworkConnectivityConfigurationRequest) *settings.NetworkConnectivityConfiguration); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settings.NetworkConnectivityConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, settings.GetNetworkConnectivityConfigurationRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetworkConnectivityConfiguration'
type MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfiguration_Call struct {
	*mock.Call
}

// GetNetworkConnectivityConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - request settings.GetNetworkConnectivityConfigurationRequest
func (_e *MockNetworkConnectivityAPIInterface_Expecter) GetNetworkConnectivityConfiguration(ctx interface{}, request interface{}) *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfiguration_Call {
	return &MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfiguration_Call{Call: _e.mock.On("GetNetworkConnectivityConfiguration", ctx, request)}
}

func (_c *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfiguration_Call) Run(run func(ctx context.Context, request settings.GetNetworkConnectivityConfigurationRequest)) *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(settings.GetNetworkConnectivityConfigurationRequest))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfiguration_Call) Return(_a0 *settings.NetworkConnectivityConfiguration, _a1 error) *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfiguration_Call) RunAndReturn(run func(context.Context, settings.GetNetworkConnectivityConfigurationRequest) (*settings.NetworkConnectivityConfiguration, error)) *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId provides a mock function with given fields: ctx, networkConnectivityConfigId
func (_m *MockNetworkConnectivityAPIInterface) GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId(ctx context.Context, networkConnectivityConfigId string) (*settings.NetworkConnectivityConfiguration, error) {
	ret := _m.Called(ctx, networkConnectivityConfigId)

	if len(ret) == 0 {
		panic("no return value specified for GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId")
	}

	var r0 *settings.NetworkConnectivityConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*settings.NetworkConnectivityConfiguration, error)); ok {
		return rf(ctx, networkConnectivityConfigId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *settings.NetworkConnectivityConfiguration); ok {
		r0 = rf(ctx, networkConnectivityConfigId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settings.NetworkConnectivityConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, networkConnectivityConfigId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId'
type MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call struct {
	*mock.Call
}

// GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId is a helper method to define mock.On call
//   - ctx context.Context
//   - networkConnectivityConfigId string
func (_e *MockNetworkConnectivityAPIInterface_Expecter) GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId(ctx interface{}, networkConnectivityConfigId interface{}) *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call {
	return &MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call{Call: _e.mock.On("GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId", ctx, networkConnectivityConfigId)}
}

func (_c *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call) Run(run func(ctx context.Context, networkConnectivityConfigId string)) *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call) Return(_a0 *settings.NetworkConnectivityConfiguration, _a1 error) *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call) RunAndReturn(run func(context.Context, string) (*settings.NetworkConnectivityConfiguration, error)) *MockNetworkConnectivityAPIInterface_GetNetworkConnectivityConfigurationByNetworkConnectivityConfigId_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateEndpointRule provides a mock function with given fields: ctx, request
func (_m *MockNetworkConnectivityAPIInterface) GetPrivateEndpointRule(ctx context.Context, request settings.GetPrivateEndpointRuleRequest) (*settings.NccAzurePrivateEndpointRule, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateEndpointRule")
	}

	var r0 *settings.NccAzurePrivateEndpointRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, settings.GetPrivateEndpointRuleRequest) (*settings.NccAzurePrivateEndpointRule, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, settings.GetPrivateEndpointRuleRequest) *settings.NccAzurePrivateEndpointRule); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settings.NccAzurePrivateEndpointRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, settings.GetPrivateEndpointRuleRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNetworkConnectivityAPIInterface_GetPrivateEndpointRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateEndpointRule'
type MockNetworkConnectivityAPIInterface_GetPrivateEndpointRule_Call struct {
	*mock.Call
}

// GetPrivateEndpointRule is a helper method to define mock.On call
//   - ctx context.Context
//   - request settings.GetPrivateEndpointRuleRequest
func (_e *MockNetworkConnectivityAPIInterface_Expecter) GetPrivateEndpointRule(ctx interface{}, request interface{}) *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRule_Call {
	return &MockNetworkConnectivityAPIInterface_GetPrivateEndpointRule_Call{Call: _e.mock.On("GetPrivateEndpointRule", ctx, request)}
}

func (_c *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRule_Call) Run(run func(ctx context.Context, request settings.GetPrivateEndpointRuleRequest)) *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(settings.GetPrivateEndpointRuleRequest))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRule_Call) Return(_a0 *settings.NccAzurePrivateEndpointRule, _a1 error) *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRule_Call) RunAndReturn(run func(context.Context, settings.GetPrivateEndpointRuleRequest) (*settings.NccAzurePrivateEndpointRule, error)) *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId provides a mock function with given fields: ctx, networkConnectivityConfigId, privateEndpointRuleId
func (_m *MockNetworkConnectivityAPIInterface) GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId(ctx context.Context, networkConnectivityConfigId string, privateEndpointRuleId string) (*settings.NccAzurePrivateEndpointRule, error) {
	ret := _m.Called(ctx, networkConnectivityConfigId, privateEndpointRuleId)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId")
	}

	var r0 *settings.NccAzurePrivateEndpointRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*settings.NccAzurePrivateEndpointRule, error)); ok {
		return rf(ctx, networkConnectivityConfigId, privateEndpointRuleId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *settings.NccAzurePrivateEndpointRule); ok {
		r0 = rf(ctx, networkConnectivityConfigId, privateEndpointRuleId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settings.NccAzurePrivateEndpointRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, networkConnectivityConfigId, privateEndpointRuleId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNetworkConnectivityAPIInterface_GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId'
type MockNetworkConnectivityAPIInterface_GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call struct {
	*mock.Call
}

// GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId is a helper method to define mock.On call
//   - ctx context.Context
//   - networkConnectivityConfigId string
//   - privateEndpointRuleId string
func (_e *MockNetworkConnectivityAPIInterface_Expecter) GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId(ctx interface{}, networkConnectivityConfigId interface{}, privateEndpointRuleId interface{}) *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call {
	return &MockNetworkConnectivityAPIInterface_GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call{Call: _e.mock.On("GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId", ctx, networkConnectivityConfigId, privateEndpointRuleId)}
}

func (_c *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call) Run(run func(ctx context.Context, networkConnectivityConfigId string, privateEndpointRuleId string)) *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call) Return(_a0 *settings.NccAzurePrivateEndpointRule, _a1 error) *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call) RunAndReturn(run func(context.Context, string, string) (*settings.NccAzurePrivateEndpointRule, error)) *MockNetworkConnectivityAPIInterface_GetPrivateEndpointRuleByNetworkConnectivityConfigIdAndPrivateEndpointRuleId_Call {
	_c.Call.Return(run)
	return _c
}

// Impl provides a mock function with given fields:
func (_m *MockNetworkConnectivityAPIInterface) Impl() settings.NetworkConnectivityService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Impl")
	}

	var r0 settings.NetworkConnectivityService
	if rf, ok := ret.Get(0).(func() settings.NetworkConnectivityService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(settings.NetworkConnectivityService)
		}
	}

	return r0
}

// MockNetworkConnectivityAPIInterface_Impl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Impl'
type MockNetworkConnectivityAPIInterface_Impl_Call struct {
	*mock.Call
}

// Impl is a helper method to define mock.On call
func (_e *MockNetworkConnectivityAPIInterface_Expecter) Impl() *MockNetworkConnectivityAPIInterface_Impl_Call {
	return &MockNetworkConnectivityAPIInterface_Impl_Call{Call: _e.mock.On("Impl")}
}

func (_c *MockNetworkConnectivityAPIInterface_Impl_Call) Run(run func()) *MockNetworkConnectivityAPIInterface_Impl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_Impl_Call) Return(_a0 settings.NetworkConnectivityService) *MockNetworkConnectivityAPIInterface_Impl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_Impl_Call) RunAndReturn(run func() settings.NetworkConnectivityService) *MockNetworkConnectivityAPIInterface_Impl_Call {
	_c.Call.Return(run)
	return _c
}

// ListNetworkConnectivityConfigurations provides a mock function with given fields: ctx, request
func (_m *MockNetworkConnectivityAPIInterface) ListNetworkConnectivityConfigurations(ctx context.Context, request settings.ListNetworkConnectivityConfigurationsRequest) *listing.PaginatingIterator[settings.ListNetworkConnectivityConfigurationsRequest, *settings.ListNetworkConnectivityConfigurationsResponse, settings.NetworkConnectivityConfiguration] {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ListNetworkConnectivityConfigurations")
	}

	var r0 *listing.PaginatingIterator[settings.ListNetworkConnectivityConfigurationsRequest, *settings.ListNetworkConnectivityConfigurationsResponse, settings.NetworkConnectivityConfiguration]
	if rf, ok := ret.Get(0).(func(context.Context, settings.ListNetworkConnectivityConfigurationsRequest) *listing.PaginatingIterator[settings.ListNetworkConnectivityConfigurationsRequest, *settings.ListNetworkConnectivityConfigurationsResponse, settings.NetworkConnectivityConfiguration]); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*listing.PaginatingIterator[settings.ListNetworkConnectivityConfigurationsRequest, *settings.ListNetworkConnectivityConfigurationsResponse, settings.NetworkConnectivityConfiguration])
		}
	}

	return r0
}

// MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNetworkConnectivityConfigurations'
type MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurations_Call struct {
	*mock.Call
}

// ListNetworkConnectivityConfigurations is a helper method to define mock.On call
//   - ctx context.Context
//   - request settings.ListNetworkConnectivityConfigurationsRequest
func (_e *MockNetworkConnectivityAPIInterface_Expecter) ListNetworkConnectivityConfigurations(ctx interface{}, request interface{}) *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurations_Call {
	return &MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurations_Call{Call: _e.mock.On("ListNetworkConnectivityConfigurations", ctx, request)}
}

func (_c *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurations_Call) Run(run func(ctx context.Context, request settings.ListNetworkConnectivityConfigurationsRequest)) *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(settings.ListNetworkConnectivityConfigurationsRequest))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurations_Call) Return(_a0 *listing.PaginatingIterator[settings.ListNetworkConnectivityConfigurationsRequest, *settings.ListNetworkConnectivityConfigurationsResponse, settings.NetworkConnectivityConfiguration]) *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurations_Call) RunAndReturn(run func(context.Context, settings.ListNetworkConnectivityConfigurationsRequest) *listing.PaginatingIterator[settings.ListNetworkConnectivityConfigurationsRequest, *settings.ListNetworkConnectivityConfigurationsResponse, settings.NetworkConnectivityConfiguration]) *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurations_Call {
	_c.Call.Return(run)
	return _c
}

// ListNetworkConnectivityConfigurationsAll provides a mock function with given fields: ctx, request
func (_m *MockNetworkConnectivityAPIInterface) ListNetworkConnectivityConfigurationsAll(ctx context.Context, request settings.ListNetworkConnectivityConfigurationsRequest) ([]settings.NetworkConnectivityConfiguration, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ListNetworkConnectivityConfigurationsAll")
	}

	var r0 []settings.NetworkConnectivityConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, settings.ListNetworkConnectivityConfigurationsRequest) ([]settings.NetworkConnectivityConfiguration, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, settings.ListNetworkConnectivityConfigurationsRequest) []settings.NetworkConnectivityConfiguration); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]settings.NetworkConnectivityConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, settings.ListNetworkConnectivityConfigurationsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurationsAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNetworkConnectivityConfigurationsAll'
type MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurationsAll_Call struct {
	*mock.Call
}

// ListNetworkConnectivityConfigurationsAll is a helper method to define mock.On call
//   - ctx context.Context
//   - request settings.ListNetworkConnectivityConfigurationsRequest
func (_e *MockNetworkConnectivityAPIInterface_Expecter) ListNetworkConnectivityConfigurationsAll(ctx interface{}, request interface{}) *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurationsAll_Call {
	return &MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurationsAll_Call{Call: _e.mock.On("ListNetworkConnectivityConfigurationsAll", ctx, request)}
}

func (_c *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurationsAll_Call) Run(run func(ctx context.Context, request settings.ListNetworkConnectivityConfigurationsRequest)) *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurationsAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(settings.ListNetworkConnectivityConfigurationsRequest))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurationsAll_Call) Return(_a0 []settings.NetworkConnectivityConfiguration, _a1 error) *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurationsAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurationsAll_Call) RunAndReturn(run func(context.Context, settings.ListNetworkConnectivityConfigurationsRequest) ([]settings.NetworkConnectivityConfiguration, error)) *MockNetworkConnectivityAPIInterface_ListNetworkConnectivityConfigurationsAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListPrivateEndpointRules provides a mock function with given fields: ctx, request
func (_m *MockNetworkConnectivityAPIInterface) ListPrivateEndpointRules(ctx context.Context, request settings.ListPrivateEndpointRulesRequest) *listing.PaginatingIterator[settings.ListPrivateEndpointRulesRequest, *settings.ListNccAzurePrivateEndpointRulesResponse, settings.NccAzurePrivateEndpointRule] {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ListPrivateEndpointRules")
	}

	var r0 *listing.PaginatingIterator[settings.ListPrivateEndpointRulesRequest, *settings.ListNccAzurePrivateEndpointRulesResponse, settings.NccAzurePrivateEndpointRule]
	if rf, ok := ret.Get(0).(func(context.Context, settings.ListPrivateEndpointRulesRequest) *listing.PaginatingIterator[settings.ListPrivateEndpointRulesRequest, *settings.ListNccAzurePrivateEndpointRulesResponse, settings.NccAzurePrivateEndpointRule]); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*listing.PaginatingIterator[settings.ListPrivateEndpointRulesRequest, *settings.ListNccAzurePrivateEndpointRulesResponse, settings.NccAzurePrivateEndpointRule])
		}
	}

	return r0
}

// MockNetworkConnectivityAPIInterface_ListPrivateEndpointRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPrivateEndpointRules'
type MockNetworkConnectivityAPIInterface_ListPrivateEndpointRules_Call struct {
	*mock.Call
}

// ListPrivateEndpointRules is a helper method to define mock.On call
//   - ctx context.Context
//   - request settings.ListPrivateEndpointRulesRequest
func (_e *MockNetworkConnectivityAPIInterface_Expecter) ListPrivateEndpointRules(ctx interface{}, request interface{}) *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRules_Call {
	return &MockNetworkConnectivityAPIInterface_ListPrivateEndpointRules_Call{Call: _e.mock.On("ListPrivateEndpointRules", ctx, request)}
}

func (_c *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRules_Call) Run(run func(ctx context.Context, request settings.ListPrivateEndpointRulesRequest)) *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(settings.ListPrivateEndpointRulesRequest))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRules_Call) Return(_a0 *listing.PaginatingIterator[settings.ListPrivateEndpointRulesRequest, *settings.ListNccAzurePrivateEndpointRulesResponse, settings.NccAzurePrivateEndpointRule]) *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRules_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRules_Call) RunAndReturn(run func(context.Context, settings.ListPrivateEndpointRulesRequest) *listing.PaginatingIterator[settings.ListPrivateEndpointRulesRequest, *settings.ListNccAzurePrivateEndpointRulesResponse, settings.NccAzurePrivateEndpointRule]) *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRules_Call {
	_c.Call.Return(run)
	return _c
}

// ListPrivateEndpointRulesAll provides a mock function with given fields: ctx, request
func (_m *MockNetworkConnectivityAPIInterface) ListPrivateEndpointRulesAll(ctx context.Context, request settings.ListPrivateEndpointRulesRequest) ([]settings.NccAzurePrivateEndpointRule, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ListPrivateEndpointRulesAll")
	}

	var r0 []settings.NccAzurePrivateEndpointRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, settings.ListPrivateEndpointRulesRequest) ([]settings.NccAzurePrivateEndpointRule, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, settings.ListPrivateEndpointRulesRequest) []settings.NccAzurePrivateEndpointRule); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]settings.NccAzurePrivateEndpointRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, settings.ListPrivateEndpointRulesRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPrivateEndpointRulesAll'
type MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesAll_Call struct {
	*mock.Call
}

// ListPrivateEndpointRulesAll is a helper method to define mock.On call
//   - ctx context.Context
//   - request settings.ListPrivateEndpointRulesRequest
func (_e *MockNetworkConnectivityAPIInterface_Expecter) ListPrivateEndpointRulesAll(ctx interface{}, request interface{}) *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesAll_Call {
	return &MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesAll_Call{Call: _e.mock.On("ListPrivateEndpointRulesAll", ctx, request)}
}

func (_c *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesAll_Call) Run(run func(ctx context.Context, request settings.ListPrivateEndpointRulesRequest)) *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(settings.ListPrivateEndpointRulesRequest))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesAll_Call) Return(_a0 []settings.NccAzurePrivateEndpointRule, _a1 error) *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesAll_Call) RunAndReturn(run func(context.Context, settings.ListPrivateEndpointRulesRequest) ([]settings.NccAzurePrivateEndpointRule, error)) *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListPrivateEndpointRulesByNetworkConnectivityConfigId provides a mock function with given fields: ctx, networkConnectivityConfigId
func (_m *MockNetworkConnectivityAPIInterface) ListPrivateEndpointRulesByNetworkConnectivityConfigId(ctx context.Context, networkConnectivityConfigId string) (*settings.ListNccAzurePrivateEndpointRulesResponse, error) {
	ret := _m.Called(ctx, networkConnectivityConfigId)

	if len(ret) == 0 {
		panic("no return value specified for ListPrivateEndpointRulesByNetworkConnectivityConfigId")
	}

	var r0 *settings.ListNccAzurePrivateEndpointRulesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*settings.ListNccAzurePrivateEndpointRulesResponse, error)); ok {
		return rf(ctx, networkConnectivityConfigId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *settings.ListNccAzurePrivateEndpointRulesResponse); ok {
		r0 = rf(ctx, networkConnectivityConfigId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settings.ListNccAzurePrivateEndpointRulesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, networkConnectivityConfigId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesByNetworkConnectivityConfigId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPrivateEndpointRulesByNetworkConnectivityConfigId'
type MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesByNetworkConnectivityConfigId_Call struct {
	*mock.Call
}

// ListPrivateEndpointRulesByNetworkConnectivityConfigId is a helper method to define mock.On call
//   - ctx context.Context
//   - networkConnectivityConfigId string
func (_e *MockNetworkConnectivityAPIInterface_Expecter) ListPrivateEndpointRulesByNetworkConnectivityConfigId(ctx interface{}, networkConnectivityConfigId interface{}) *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesByNetworkConnectivityConfigId_Call {
	return &MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesByNetworkConnectivityConfigId_Call{Call: _e.mock.On("ListPrivateEndpointRulesByNetworkConnectivityConfigId", ctx, networkConnectivityConfigId)}
}

func (_c *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesByNetworkConnectivityConfigId_Call) Run(run func(ctx context.Context, networkConnectivityConfigId string)) *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesByNetworkConnectivityConfigId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesByNetworkConnectivityConfigId_Call) Return(_a0 *settings.ListNccAzurePrivateEndpointRulesResponse, _a1 error) *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesByNetworkConnectivityConfigId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesByNetworkConnectivityConfigId_Call) RunAndReturn(run func(context.Context, string) (*settings.ListNccAzurePrivateEndpointRulesResponse, error)) *MockNetworkConnectivityAPIInterface_ListPrivateEndpointRulesByNetworkConnectivityConfigId_Call {
	_c.Call.Return(run)
	return _c
}

// WithImpl provides a mock function with given fields: impl
func (_m *MockNetworkConnectivityAPIInterface) WithImpl(impl settings.NetworkConnectivityService) settings.NetworkConnectivityAPIInterface {
	ret := _m.Called(impl)

	if len(ret) == 0 {
		panic("no return value specified for WithImpl")
	}

	var r0 settings.NetworkConnectivityAPIInterface
	if rf, ok := ret.Get(0).(func(settings.NetworkConnectivityService) settings.NetworkConnectivityAPIInterface); ok {
		r0 = rf(impl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(settings.NetworkConnectivityAPIInterface)
		}
	}

	return r0
}

// MockNetworkConnectivityAPIInterface_WithImpl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithImpl'
type MockNetworkConnectivityAPIInterface_WithImpl_Call struct {
	*mock.Call
}

// WithImpl is a helper method to define mock.On call
//   - impl settings.NetworkConnectivityService
func (_e *MockNetworkConnectivityAPIInterface_Expecter) WithImpl(impl interface{}) *MockNetworkConnectivityAPIInterface_WithImpl_Call {
	return &MockNetworkConnectivityAPIInterface_WithImpl_Call{Call: _e.mock.On("WithImpl", impl)}
}

func (_c *MockNetworkConnectivityAPIInterface_WithImpl_Call) Run(run func(impl settings.NetworkConnectivityService)) *MockNetworkConnectivityAPIInterface_WithImpl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(settings.NetworkConnectivityService))
	})
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_WithImpl_Call) Return(_a0 settings.NetworkConnectivityAPIInterface) *MockNetworkConnectivityAPIInterface_WithImpl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNetworkConnectivityAPIInterface_WithImpl_Call) RunAndReturn(run func(settings.NetworkConnectivityService) settings.NetworkConnectivityAPIInterface) *MockNetworkConnectivityAPIInterface_WithImpl_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNetworkConnectivityAPIInterface creates a new instance of MockNetworkConnectivityAPIInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNetworkConnectivityAPIInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNetworkConnectivityAPIInterface {
	mock := &MockNetworkConnectivityAPIInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
