// Code generated by mockery v2.38.0. DO NOT EDIT.

package iam

import (
	context "context"

	listing "github.com/databricks/databricks-sdk-go/listing"
	iam "github.com/databricks/databricks-sdk-go/service/iam"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountUsersAPIInterface is an autogenerated mock type for the AccountUsersAPIInterface type
type MockAccountUsersAPIInterface struct {
	mock.Mock
}

type MockAccountUsersAPIInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountUsersAPIInterface) EXPECT() *MockAccountUsersAPIInterface_Expecter {
	return &MockAccountUsersAPIInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, request
func (_m *MockAccountUsersAPIInterface) Create(ctx context.Context, request iam.User) (*iam.User, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *iam.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, iam.User) (*iam.User, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, iam.User) *iam.User); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iam.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, iam.User) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountUsersAPIInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountUsersAPIInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request iam.User
func (_e *MockAccountUsersAPIInterface_Expecter) Create(ctx interface{}, request interface{}) *MockAccountUsersAPIInterface_Create_Call {
	return &MockAccountUsersAPIInterface_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockAccountUsersAPIInterface_Create_Call) Run(run func(ctx context.Context, request iam.User)) *MockAccountUsersAPIInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(iam.User))
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_Create_Call) Return(_a0 *iam.User, _a1 error) *MockAccountUsersAPIInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountUsersAPIInterface_Create_Call) RunAndReturn(run func(context.Context, iam.User) (*iam.User, error)) *MockAccountUsersAPIInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, request
func (_m *MockAccountUsersAPIInterface) Delete(ctx context.Context, request iam.DeleteAccountUserRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, iam.DeleteAccountUserRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountUsersAPIInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAccountUsersAPIInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - request iam.DeleteAccountUserRequest
func (_e *MockAccountUsersAPIInterface_Expecter) Delete(ctx interface{}, request interface{}) *MockAccountUsersAPIInterface_Delete_Call {
	return &MockAccountUsersAPIInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, request)}
}

func (_c *MockAccountUsersAPIInterface_Delete_Call) Run(run func(ctx context.Context, request iam.DeleteAccountUserRequest)) *MockAccountUsersAPIInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(iam.DeleteAccountUserRequest))
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_Delete_Call) Return(_a0 error) *MockAccountUsersAPIInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountUsersAPIInterface_Delete_Call) RunAndReturn(run func(context.Context, iam.DeleteAccountUserRequest) error) *MockAccountUsersAPIInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteById provides a mock function with given fields: ctx, id
func (_m *MockAccountUsersAPIInterface) DeleteById(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountUsersAPIInterface_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockAccountUsersAPIInterface_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAccountUsersAPIInterface_Expecter) DeleteById(ctx interface{}, id interface{}) *MockAccountUsersAPIInterface_DeleteById_Call {
	return &MockAccountUsersAPIInterface_DeleteById_Call{Call: _e.mock.On("DeleteById", ctx, id)}
}

func (_c *MockAccountUsersAPIInterface_DeleteById_Call) Run(run func(ctx context.Context, id string)) *MockAccountUsersAPIInterface_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_DeleteById_Call) Return(_a0 error) *MockAccountUsersAPIInterface_DeleteById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountUsersAPIInterface_DeleteById_Call) RunAndReturn(run func(context.Context, string) error) *MockAccountUsersAPIInterface_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, request
func (_m *MockAccountUsersAPIInterface) Get(ctx context.Context, request iam.GetAccountUserRequest) (*iam.User, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *iam.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, iam.GetAccountUserRequest) (*iam.User, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, iam.GetAccountUserRequest) *iam.User); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iam.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, iam.GetAccountUserRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountUsersAPIInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAccountUsersAPIInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - request iam.GetAccountUserRequest
func (_e *MockAccountUsersAPIInterface_Expecter) Get(ctx interface{}, request interface{}) *MockAccountUsersAPIInterface_Get_Call {
	return &MockAccountUsersAPIInterface_Get_Call{Call: _e.mock.On("Get", ctx, request)}
}

func (_c *MockAccountUsersAPIInterface_Get_Call) Run(run func(ctx context.Context, request iam.GetAccountUserRequest)) *MockAccountUsersAPIInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(iam.GetAccountUserRequest))
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_Get_Call) Return(_a0 *iam.User, _a1 error) *MockAccountUsersAPIInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountUsersAPIInterface_Get_Call) RunAndReturn(run func(context.Context, iam.GetAccountUserRequest) (*iam.User, error)) *MockAccountUsersAPIInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: ctx, id
func (_m *MockAccountUsersAPIInterface) GetById(ctx context.Context, id string) (*iam.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *iam.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*iam.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *iam.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iam.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountUsersAPIInterface_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockAccountUsersAPIInterface_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAccountUsersAPIInterface_Expecter) GetById(ctx interface{}, id interface{}) *MockAccountUsersAPIInterface_GetById_Call {
	return &MockAccountUsersAPIInterface_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockAccountUsersAPIInterface_GetById_Call) Run(run func(ctx context.Context, id string)) *MockAccountUsersAPIInterface_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_GetById_Call) Return(_a0 *iam.User, _a1 error) *MockAccountUsersAPIInterface_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountUsersAPIInterface_GetById_Call) RunAndReturn(run func(context.Context, string) (*iam.User, error)) *MockAccountUsersAPIInterface_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserName provides a mock function with given fields: ctx, name
func (_m *MockAccountUsersAPIInterface) GetByUserName(ctx context.Context, name string) (*iam.User, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserName")
	}

	var r0 *iam.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*iam.User, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *iam.User); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iam.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountUsersAPIInterface_GetByUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserName'
type MockAccountUsersAPIInterface_GetByUserName_Call struct {
	*mock.Call
}

// GetByUserName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAccountUsersAPIInterface_Expecter) GetByUserName(ctx interface{}, name interface{}) *MockAccountUsersAPIInterface_GetByUserName_Call {
	return &MockAccountUsersAPIInterface_GetByUserName_Call{Call: _e.mock.On("GetByUserName", ctx, name)}
}

func (_c *MockAccountUsersAPIInterface_GetByUserName_Call) Run(run func(ctx context.Context, name string)) *MockAccountUsersAPIInterface_GetByUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_GetByUserName_Call) Return(_a0 *iam.User, _a1 error) *MockAccountUsersAPIInterface_GetByUserName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountUsersAPIInterface_GetByUserName_Call) RunAndReturn(run func(context.Context, string) (*iam.User, error)) *MockAccountUsersAPIInterface_GetByUserName_Call {
	_c.Call.Return(run)
	return _c
}

// Impl provides a mock function with given fields:
func (_m *MockAccountUsersAPIInterface) Impl() iam.AccountUsersService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Impl")
	}

	var r0 iam.AccountUsersService
	if rf, ok := ret.Get(0).(func() iam.AccountUsersService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iam.AccountUsersService)
		}
	}

	return r0
}

// MockAccountUsersAPIInterface_Impl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Impl'
type MockAccountUsersAPIInterface_Impl_Call struct {
	*mock.Call
}

// Impl is a helper method to define mock.On call
func (_e *MockAccountUsersAPIInterface_Expecter) Impl() *MockAccountUsersAPIInterface_Impl_Call {
	return &MockAccountUsersAPIInterface_Impl_Call{Call: _e.mock.On("Impl")}
}

func (_c *MockAccountUsersAPIInterface_Impl_Call) Run(run func()) *MockAccountUsersAPIInterface_Impl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_Impl_Call) Return(_a0 iam.AccountUsersService) *MockAccountUsersAPIInterface_Impl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountUsersAPIInterface_Impl_Call) RunAndReturn(run func() iam.AccountUsersService) *MockAccountUsersAPIInterface_Impl_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, request
func (_m *MockAccountUsersAPIInterface) List(ctx context.Context, request iam.ListAccountUsersRequest) *listing.DeduplicatingIterator[iam.User, string] {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *listing.DeduplicatingIterator[iam.User, string]
	if rf, ok := ret.Get(0).(func(context.Context, iam.ListAccountUsersRequest) *listing.DeduplicatingIterator[iam.User, string]); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*listing.DeduplicatingIterator[iam.User, string])
		}
	}

	return r0
}

// MockAccountUsersAPIInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAccountUsersAPIInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - request iam.ListAccountUsersRequest
func (_e *MockAccountUsersAPIInterface_Expecter) List(ctx interface{}, request interface{}) *MockAccountUsersAPIInterface_List_Call {
	return &MockAccountUsersAPIInterface_List_Call{Call: _e.mock.On("List", ctx, request)}
}

func (_c *MockAccountUsersAPIInterface_List_Call) Run(run func(ctx context.Context, request iam.ListAccountUsersRequest)) *MockAccountUsersAPIInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(iam.ListAccountUsersRequest))
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_List_Call) Return(_a0 *listing.DeduplicatingIterator[iam.User, string]) *MockAccountUsersAPIInterface_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountUsersAPIInterface_List_Call) RunAndReturn(run func(context.Context, iam.ListAccountUsersRequest) *listing.DeduplicatingIterator[iam.User, string]) *MockAccountUsersAPIInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx, request
func (_m *MockAccountUsersAPIInterface) ListAll(ctx context.Context, request iam.ListAccountUsersRequest) ([]iam.User, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []iam.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, iam.ListAccountUsersRequest) ([]iam.User, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, iam.ListAccountUsersRequest) []iam.User); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iam.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, iam.ListAccountUsersRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountUsersAPIInterface_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockAccountUsersAPIInterface_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
//   - request iam.ListAccountUsersRequest
func (_e *MockAccountUsersAPIInterface_Expecter) ListAll(ctx interface{}, request interface{}) *MockAccountUsersAPIInterface_ListAll_Call {
	return &MockAccountUsersAPIInterface_ListAll_Call{Call: _e.mock.On("ListAll", ctx, request)}
}

func (_c *MockAccountUsersAPIInterface_ListAll_Call) Run(run func(ctx context.Context, request iam.ListAccountUsersRequest)) *MockAccountUsersAPIInterface_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(iam.ListAccountUsersRequest))
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_ListAll_Call) Return(_a0 []iam.User, _a1 error) *MockAccountUsersAPIInterface_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountUsersAPIInterface_ListAll_Call) RunAndReturn(run func(context.Context, iam.ListAccountUsersRequest) ([]iam.User, error)) *MockAccountUsersAPIInterface_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, request
func (_m *MockAccountUsersAPIInterface) Patch(ctx context.Context, request iam.PartialUpdate) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, iam.PartialUpdate) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountUsersAPIInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockAccountUsersAPIInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - request iam.PartialUpdate
func (_e *MockAccountUsersAPIInterface_Expecter) Patch(ctx interface{}, request interface{}) *MockAccountUsersAPIInterface_Patch_Call {
	return &MockAccountUsersAPIInterface_Patch_Call{Call: _e.mock.On("Patch", ctx, request)}
}

func (_c *MockAccountUsersAPIInterface_Patch_Call) Run(run func(ctx context.Context, request iam.PartialUpdate)) *MockAccountUsersAPIInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(iam.PartialUpdate))
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_Patch_Call) Return(_a0 error) *MockAccountUsersAPIInterface_Patch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountUsersAPIInterface_Patch_Call) RunAndReturn(run func(context.Context, iam.PartialUpdate) error) *MockAccountUsersAPIInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, request
func (_m *MockAccountUsersAPIInterface) Update(ctx context.Context, request iam.User) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, iam.User) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountUsersAPIInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountUsersAPIInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - request iam.User
func (_e *MockAccountUsersAPIInterface_Expecter) Update(ctx interface{}, request interface{}) *MockAccountUsersAPIInterface_Update_Call {
	return &MockAccountUsersAPIInterface_Update_Call{Call: _e.mock.On("Update", ctx, request)}
}

func (_c *MockAccountUsersAPIInterface_Update_Call) Run(run func(ctx context.Context, request iam.User)) *MockAccountUsersAPIInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(iam.User))
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_Update_Call) Return(_a0 error) *MockAccountUsersAPIInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountUsersAPIInterface_Update_Call) RunAndReturn(run func(context.Context, iam.User) error) *MockAccountUsersAPIInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UserUserNameToIdMap provides a mock function with given fields: ctx, request
func (_m *MockAccountUsersAPIInterface) UserUserNameToIdMap(ctx context.Context, request iam.ListAccountUsersRequest) (map[string]string, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UserUserNameToIdMap")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, iam.ListAccountUsersRequest) (map[string]string, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, iam.ListAccountUsersRequest) map[string]string); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, iam.ListAccountUsersRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountUsersAPIInterface_UserUserNameToIdMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserUserNameToIdMap'
type MockAccountUsersAPIInterface_UserUserNameToIdMap_Call struct {
	*mock.Call
}

// UserUserNameToIdMap is a helper method to define mock.On call
//   - ctx context.Context
//   - request iam.ListAccountUsersRequest
func (_e *MockAccountUsersAPIInterface_Expecter) UserUserNameToIdMap(ctx interface{}, request interface{}) *MockAccountUsersAPIInterface_UserUserNameToIdMap_Call {
	return &MockAccountUsersAPIInterface_UserUserNameToIdMap_Call{Call: _e.mock.On("UserUserNameToIdMap", ctx, request)}
}

func (_c *MockAccountUsersAPIInterface_UserUserNameToIdMap_Call) Run(run func(ctx context.Context, request iam.ListAccountUsersRequest)) *MockAccountUsersAPIInterface_UserUserNameToIdMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(iam.ListAccountUsersRequest))
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_UserUserNameToIdMap_Call) Return(_a0 map[string]string, _a1 error) *MockAccountUsersAPIInterface_UserUserNameToIdMap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountUsersAPIInterface_UserUserNameToIdMap_Call) RunAndReturn(run func(context.Context, iam.ListAccountUsersRequest) (map[string]string, error)) *MockAccountUsersAPIInterface_UserUserNameToIdMap_Call {
	_c.Call.Return(run)
	return _c
}

// WithImpl provides a mock function with given fields: impl
func (_m *MockAccountUsersAPIInterface) WithImpl(impl iam.AccountUsersService) iam.AccountUsersAPIInterface {
	ret := _m.Called(impl)

	if len(ret) == 0 {
		panic("no return value specified for WithImpl")
	}

	var r0 iam.AccountUsersAPIInterface
	if rf, ok := ret.Get(0).(func(iam.AccountUsersService) iam.AccountUsersAPIInterface); ok {
		r0 = rf(impl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iam.AccountUsersAPIInterface)
		}
	}

	return r0
}

// MockAccountUsersAPIInterface_WithImpl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithImpl'
type MockAccountUsersAPIInterface_WithImpl_Call struct {
	*mock.Call
}

// WithImpl is a helper method to define mock.On call
//   - impl iam.AccountUsersService
func (_e *MockAccountUsersAPIInterface_Expecter) WithImpl(impl interface{}) *MockAccountUsersAPIInterface_WithImpl_Call {
	return &MockAccountUsersAPIInterface_WithImpl_Call{Call: _e.mock.On("WithImpl", impl)}
}

func (_c *MockAccountUsersAPIInterface_WithImpl_Call) Run(run func(impl iam.AccountUsersService)) *MockAccountUsersAPIInterface_WithImpl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(iam.AccountUsersService))
	})
	return _c
}

func (_c *MockAccountUsersAPIInterface_WithImpl_Call) Return(_a0 iam.AccountUsersAPIInterface) *MockAccountUsersAPIInterface_WithImpl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountUsersAPIInterface_WithImpl_Call) RunAndReturn(run func(iam.AccountUsersService) iam.AccountUsersAPIInterface) *MockAccountUsersAPIInterface_WithImpl_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountUsersAPIInterface creates a new instance of MockAccountUsersAPIInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountUsersAPIInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountUsersAPIInterface {
	mock := &MockAccountUsersAPIInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
