// Code generated by mockery v2.53.2. DO NOT EDIT.

package postgres

import (
	context "context"

	api "github.com/databricks/databricks-sdk-go/experimental/api"

	mock "github.com/stretchr/testify/mock"

	postgres "github.com/databricks/databricks-sdk-go/service/postgres"
)

// MockUpdateRoleOperationInterface is an autogenerated mock type for the UpdateRoleOperationInterface type
type MockUpdateRoleOperationInterface struct {
	mock.Mock
}

type MockUpdateRoleOperationInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateRoleOperationInterface) EXPECT() *MockUpdateRoleOperationInterface_Expecter {
	return &MockUpdateRoleOperationInterface_Expecter{mock: &_m.Mock}
}

// Done provides a mock function with no fields
func (_m *MockUpdateRoleOperationInterface) Done() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateRoleOperationInterface_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockUpdateRoleOperationInterface_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockUpdateRoleOperationInterface_Expecter) Done() *MockUpdateRoleOperationInterface_Done_Call {
	return &MockUpdateRoleOperationInterface_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockUpdateRoleOperationInterface_Done_Call) Run(run func()) *MockUpdateRoleOperationInterface_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdateRoleOperationInterface_Done_Call) Return(_a0 bool, _a1 error) *MockUpdateRoleOperationInterface_Done_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateRoleOperationInterface_Done_Call) RunAndReturn(run func() (bool, error)) *MockUpdateRoleOperationInterface_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function with no fields
func (_m *MockUpdateRoleOperationInterface) Metadata() (*postgres.RoleOperationMetadata, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 *postgres.RoleOperationMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func() (*postgres.RoleOperationMetadata, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *postgres.RoleOperationMetadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgres.RoleOperationMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateRoleOperationInterface_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockUpdateRoleOperationInterface_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockUpdateRoleOperationInterface_Expecter) Metadata() *MockUpdateRoleOperationInterface_Metadata_Call {
	return &MockUpdateRoleOperationInterface_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockUpdateRoleOperationInterface_Metadata_Call) Run(run func()) *MockUpdateRoleOperationInterface_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdateRoleOperationInterface_Metadata_Call) Return(_a0 *postgres.RoleOperationMetadata, _a1 error) *MockUpdateRoleOperationInterface_Metadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateRoleOperationInterface_Metadata_Call) RunAndReturn(run func() (*postgres.RoleOperationMetadata, error)) *MockUpdateRoleOperationInterface_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockUpdateRoleOperationInterface) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockUpdateRoleOperationInterface_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockUpdateRoleOperationInterface_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockUpdateRoleOperationInterface_Expecter) Name() *MockUpdateRoleOperationInterface_Name_Call {
	return &MockUpdateRoleOperationInterface_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockUpdateRoleOperationInterface_Name_Call) Run(run func()) *MockUpdateRoleOperationInterface_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdateRoleOperationInterface_Name_Call) Return(_a0 string) *MockUpdateRoleOperationInterface_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateRoleOperationInterface_Name_Call) RunAndReturn(run func() string) *MockUpdateRoleOperationInterface_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with given fields: ctx, opts
func (_m *MockUpdateRoleOperationInterface) Wait(ctx context.Context, opts ...api.Option) (*postgres.Role, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 *postgres.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...api.Option) (*postgres.Role, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...api.Option) *postgres.Role); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgres.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...api.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateRoleOperationInterface_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockUpdateRoleOperationInterface_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...api.Option
func (_e *MockUpdateRoleOperationInterface_Expecter) Wait(ctx interface{}, opts ...interface{}) *MockUpdateRoleOperationInterface_Wait_Call {
	return &MockUpdateRoleOperationInterface_Wait_Call{Call: _e.mock.On("Wait",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockUpdateRoleOperationInterface_Wait_Call) Run(run func(ctx context.Context, opts ...api.Option)) *MockUpdateRoleOperationInterface_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]api.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(api.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateRoleOperationInterface_Wait_Call) Return(_a0 *postgres.Role, _a1 error) *MockUpdateRoleOperationInterface_Wait_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateRoleOperationInterface_Wait_Call) RunAndReturn(run func(context.Context, ...api.Option) (*postgres.Role, error)) *MockUpdateRoleOperationInterface_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateRoleOperationInterface creates a new instance of MockUpdateRoleOperationInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateRoleOperationInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateRoleOperationInterface {
	mock := &MockUpdateRoleOperationInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
