// Code generated by mockery v2.53.2. DO NOT EDIT.

package postgres

import (
	context "context"

	lro "github.com/databricks/databricks-sdk-go/service/common/lro"
	mock "github.com/stretchr/testify/mock"

	postgres "github.com/databricks/databricks-sdk-go/service/postgres"
)

// MockUpdateDatabaseProjectOperationInterface is an autogenerated mock type for the UpdateDatabaseProjectOperationInterface type
type MockUpdateDatabaseProjectOperationInterface struct {
	mock.Mock
}

type MockUpdateDatabaseProjectOperationInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateDatabaseProjectOperationInterface) EXPECT() *MockUpdateDatabaseProjectOperationInterface_Expecter {
	return &MockUpdateDatabaseProjectOperationInterface_Expecter{mock: &_m.Mock}
}

// Done provides a mock function with no fields
func (_m *MockUpdateDatabaseProjectOperationInterface) Done() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateDatabaseProjectOperationInterface_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockUpdateDatabaseProjectOperationInterface_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockUpdateDatabaseProjectOperationInterface_Expecter) Done() *MockUpdateDatabaseProjectOperationInterface_Done_Call {
	return &MockUpdateDatabaseProjectOperationInterface_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockUpdateDatabaseProjectOperationInterface_Done_Call) Run(run func()) *MockUpdateDatabaseProjectOperationInterface_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdateDatabaseProjectOperationInterface_Done_Call) Return(_a0 bool, _a1 error) *MockUpdateDatabaseProjectOperationInterface_Done_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateDatabaseProjectOperationInterface_Done_Call) RunAndReturn(run func() (bool, error)) *MockUpdateDatabaseProjectOperationInterface_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function with no fields
func (_m *MockUpdateDatabaseProjectOperationInterface) Metadata() (*postgres.DatabaseProjectOperationMetadata, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 *postgres.DatabaseProjectOperationMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func() (*postgres.DatabaseProjectOperationMetadata, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *postgres.DatabaseProjectOperationMetadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgres.DatabaseProjectOperationMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateDatabaseProjectOperationInterface_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockUpdateDatabaseProjectOperationInterface_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockUpdateDatabaseProjectOperationInterface_Expecter) Metadata() *MockUpdateDatabaseProjectOperationInterface_Metadata_Call {
	return &MockUpdateDatabaseProjectOperationInterface_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockUpdateDatabaseProjectOperationInterface_Metadata_Call) Run(run func()) *MockUpdateDatabaseProjectOperationInterface_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdateDatabaseProjectOperationInterface_Metadata_Call) Return(_a0 *postgres.DatabaseProjectOperationMetadata, _a1 error) *MockUpdateDatabaseProjectOperationInterface_Metadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateDatabaseProjectOperationInterface_Metadata_Call) RunAndReturn(run func() (*postgres.DatabaseProjectOperationMetadata, error)) *MockUpdateDatabaseProjectOperationInterface_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockUpdateDatabaseProjectOperationInterface) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockUpdateDatabaseProjectOperationInterface_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockUpdateDatabaseProjectOperationInterface_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockUpdateDatabaseProjectOperationInterface_Expecter) Name() *MockUpdateDatabaseProjectOperationInterface_Name_Call {
	return &MockUpdateDatabaseProjectOperationInterface_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockUpdateDatabaseProjectOperationInterface_Name_Call) Run(run func()) *MockUpdateDatabaseProjectOperationInterface_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdateDatabaseProjectOperationInterface_Name_Call) Return(_a0 string) *MockUpdateDatabaseProjectOperationInterface_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateDatabaseProjectOperationInterface_Name_Call) RunAndReturn(run func() string) *MockUpdateDatabaseProjectOperationInterface_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with given fields: ctx, opts
func (_m *MockUpdateDatabaseProjectOperationInterface) Wait(ctx context.Context, opts *lro.LroOptions) (*postgres.DatabaseProject, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 *postgres.DatabaseProject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *lro.LroOptions) (*postgres.DatabaseProject, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *lro.LroOptions) *postgres.DatabaseProject); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgres.DatabaseProject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *lro.LroOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateDatabaseProjectOperationInterface_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockUpdateDatabaseProjectOperationInterface_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *lro.LroOptions
func (_e *MockUpdateDatabaseProjectOperationInterface_Expecter) Wait(ctx interface{}, opts interface{}) *MockUpdateDatabaseProjectOperationInterface_Wait_Call {
	return &MockUpdateDatabaseProjectOperationInterface_Wait_Call{Call: _e.mock.On("Wait", ctx, opts)}
}

func (_c *MockUpdateDatabaseProjectOperationInterface_Wait_Call) Run(run func(ctx context.Context, opts *lro.LroOptions)) *MockUpdateDatabaseProjectOperationInterface_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*lro.LroOptions))
	})
	return _c
}

func (_c *MockUpdateDatabaseProjectOperationInterface_Wait_Call) Return(_a0 *postgres.DatabaseProject, _a1 error) *MockUpdateDatabaseProjectOperationInterface_Wait_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateDatabaseProjectOperationInterface_Wait_Call) RunAndReturn(run func(context.Context, *lro.LroOptions) (*postgres.DatabaseProject, error)) *MockUpdateDatabaseProjectOperationInterface_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateDatabaseProjectOperationInterface creates a new instance of MockUpdateDatabaseProjectOperationInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateDatabaseProjectOperationInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateDatabaseProjectOperationInterface {
	mock := &MockUpdateDatabaseProjectOperationInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
